// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsmdE60tgw5WHhNDqqk1RGjPl3nSrDxpQ',
    appId: '1:671603227468:web:640aa56175921946856de9',
    messagingSenderId: '671603227468',
    projectId: 'teacher-attendance-9d519',
    authDomain: 'teacher-attendance-9d519.firebaseapp.com',
    storageBucket: 'teacher-attendance-9d519.appspot.com',
    measurementId: 'G-3DR2N7T43L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnAXNtwjF1S8lyr36E_VLRsUwTJ7d4XlA',
    appId: '1:671603227468:android:0273f1150de7ff5a856de9',
    messagingSenderId: '671603227468',
    projectId: 'teacher-attendance-9d519',
    storageBucket: 'teacher-attendance-9d519.appspot.com',
  );
}
